name: climagic
on:
  schedule:
    # - cron: '* * * * *' # for test
    - cron: '0 1,13 * * *'

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout codes
      - name: run climagic.sh
        env:
          EMAIL: ${{ secrets.EMAIL }}
          SCKEY: ${{ secrets.SCKEY }}
          QQ_EMAIL: ${{ secrets.QQ_EMAIL }}
          QQ_EMAIL_PWD: ${{ secrets.QQ_EMAIL_PWD }}
        run: bash climagic.sh
